### ISSUE TITLE
Note for Version 3 Upgraders

### ISSUE THREAD

**Issue by redevill** [frux/express-csp-header#24] opened 2020-03-20 17:27 UTC
Hello, Just a friendly note for those who may have the same issues.

1. Node "Outdated" command highlighted this library while it did not highlight my **express version ^4.16.4** as being out of date. The environment detailed below did not work for me. However, after updating to **express ^4.17.3** this library started working.
2. Parse-domain is broken again, due to minimist. Deep in the hierarchy they is a lib rc that does not look like anyone is maintaining it.

My _NOT WORKING_ Environment:
- MacOs: 10.14.5
- Chrome: 80.0.3987.132
- Express: 4.16.4
- Node: 12.16.1

**Comment by frux** [comment] 2020-03-20 18:34
@redevill Hi! Sounds dissapointing but I can't reproduce it. What kind of error did you ran into?

My Environment (I don't have MacOS):
- Ubuntu 18.04
- Node: 12.16.1

**Comment by redevill** [comment] 2020-03-20 23:09
@frux - with the older version of express, it did not appear to recognize the Originating source - aka "self". Every call was registered as a problem. Even when explicitly putting in the original source page ( http://localhost:9001 ) into the CSP directive. After changing express (npm install on changed package.json) all the false positives disappeared from my chrome console.

As for the minimist dependency, npm is acting weird - good news is that this lib is no longer reporting an error.

**Comment by frux** [comment] 2020-03-21 16:21
@redevill I vainly tried to reproduce your problem with `express@4.17.1` like this
```js
const path = require('path');
const express = require('express');
const { expressCspHeader, SELF } = require('express-csp-header');

const app = express();

app.use(expressCspHeader({
    directives: {
        'script-src': [SELF]
    }
}));

app.use('/', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'index.html'));
});

app.listen(9001);
```

Can you provide minimal example of code with reproducable problem?

**Comment by redevill** [comment] 2020-03-23 14:43
Yes, I will try and give you a repro - might take me a day or two.

**Comment by redevill** [comment] 2020-04-02 14:30
I stated the wrong version above for the not working - It was 4.16.4, But even so, Something else must have changed - because I was also not able to reproduce.

**Comment by frux** [comment] 2020-04-02 15:05
Ok. I'm closing this issue. Please reopen it if you'll run into same problem again.

**Closed as completed by frux** 2020-04-02 15:05 UTC

**Comment by redevill** [comment] 2020-04-02 15:36
Will do - thanks
